#para meterlo environment en el RENDER
nest.api.url=${NEST_API_URL} 
server.port=${PORT:8080}
frontend.base.url=${FRONTEND_BASE_URL}
resend.api.key=${RESEND_API_KEY}

spring.jpa.open-in-view=false
spring.main.lazy-initialization=true

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
