spring.application.name=user
spring.profiles.active=dev

spring.security.user.name=admin
spring.security.user.password=qwerty

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME:jdibel05@gmail.com}
spring.mail.password=${MAIL_PASSWORD:vqlpcwjbftqcccpc}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true